// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"librarian/models"
)

// DeleteBooksIsbnReader is a Reader for the DeleteBooksIsbn structure.
type DeleteBooksIsbnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBooksIsbnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteBooksIsbnNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteBooksIsbnNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteBooksIsbnDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteBooksIsbnNoContent creates a DeleteBooksIsbnNoContent with default headers values
func NewDeleteBooksIsbnNoContent() *DeleteBooksIsbnNoContent {
	return &DeleteBooksIsbnNoContent{}
}

/*
DeleteBooksIsbnNoContent describes a response with status code 204, with default header values.

No content on successful delete
*/
type DeleteBooksIsbnNoContent struct {
	Payload *models.Book
}

// IsSuccess returns true when this delete books isbn no content response has a 2xx status code
func (o *DeleteBooksIsbnNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete books isbn no content response has a 3xx status code
func (o *DeleteBooksIsbnNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete books isbn no content response has a 4xx status code
func (o *DeleteBooksIsbnNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete books isbn no content response has a 5xx status code
func (o *DeleteBooksIsbnNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete books isbn no content response a status code equal to that given
func (o *DeleteBooksIsbnNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete books isbn no content response
func (o *DeleteBooksIsbnNoContent) Code() int {
	return 204
}

func (o *DeleteBooksIsbnNoContent) Error() string {
	return fmt.Sprintf("[DELETE /books/{isbn}][%d] deleteBooksIsbnNoContent  %+v", 204, o.Payload)
}

func (o *DeleteBooksIsbnNoContent) String() string {
	return fmt.Sprintf("[DELETE /books/{isbn}][%d] deleteBooksIsbnNoContent  %+v", 204, o.Payload)
}

func (o *DeleteBooksIsbnNoContent) GetPayload() *models.Book {
	return o.Payload
}

func (o *DeleteBooksIsbnNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Book)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBooksIsbnNotFound creates a DeleteBooksIsbnNotFound with default headers values
func NewDeleteBooksIsbnNotFound() *DeleteBooksIsbnNotFound {
	return &DeleteBooksIsbnNotFound{}
}

/*
DeleteBooksIsbnNotFound describes a response with status code 404, with default header values.

Book not found.
*/
type DeleteBooksIsbnNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete books isbn not found response has a 2xx status code
func (o *DeleteBooksIsbnNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete books isbn not found response has a 3xx status code
func (o *DeleteBooksIsbnNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete books isbn not found response has a 4xx status code
func (o *DeleteBooksIsbnNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete books isbn not found response has a 5xx status code
func (o *DeleteBooksIsbnNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete books isbn not found response a status code equal to that given
func (o *DeleteBooksIsbnNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete books isbn not found response
func (o *DeleteBooksIsbnNotFound) Code() int {
	return 404
}

func (o *DeleteBooksIsbnNotFound) Error() string {
	return fmt.Sprintf("[DELETE /books/{isbn}][%d] deleteBooksIsbnNotFound  %+v", 404, o.Payload)
}

func (o *DeleteBooksIsbnNotFound) String() string {
	return fmt.Sprintf("[DELETE /books/{isbn}][%d] deleteBooksIsbnNotFound  %+v", 404, o.Payload)
}

func (o *DeleteBooksIsbnNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteBooksIsbnNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBooksIsbnDefault creates a DeleteBooksIsbnDefault with default headers values
func NewDeleteBooksIsbnDefault(code int) *DeleteBooksIsbnDefault {
	return &DeleteBooksIsbnDefault{
		_statusCode: code,
	}
}

/*
DeleteBooksIsbnDefault describes a response with status code -1, with default header values.

bad input parametr/missing book
*/
type DeleteBooksIsbnDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this delete books isbn default response has a 2xx status code
func (o *DeleteBooksIsbnDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete books isbn default response has a 3xx status code
func (o *DeleteBooksIsbnDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete books isbn default response has a 4xx status code
func (o *DeleteBooksIsbnDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete books isbn default response has a 5xx status code
func (o *DeleteBooksIsbnDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete books isbn default response a status code equal to that given
func (o *DeleteBooksIsbnDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete books isbn default response
func (o *DeleteBooksIsbnDefault) Code() int {
	return o._statusCode
}

func (o *DeleteBooksIsbnDefault) Error() string {
	return fmt.Sprintf("[DELETE /books/{isbn}][%d] DeleteBooksIsbn default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteBooksIsbnDefault) String() string {
	return fmt.Sprintf("[DELETE /books/{isbn}][%d] DeleteBooksIsbn default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteBooksIsbnDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteBooksIsbnDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
