// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteBooksIsbnParams creates a new DeleteBooksIsbnParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBooksIsbnParams() *DeleteBooksIsbnParams {
	return &DeleteBooksIsbnParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBooksIsbnParamsWithTimeout creates a new DeleteBooksIsbnParams object
// with the ability to set a timeout on a request.
func NewDeleteBooksIsbnParamsWithTimeout(timeout time.Duration) *DeleteBooksIsbnParams {
	return &DeleteBooksIsbnParams{
		timeout: timeout,
	}
}

// NewDeleteBooksIsbnParamsWithContext creates a new DeleteBooksIsbnParams object
// with the ability to set a context for a request.
func NewDeleteBooksIsbnParamsWithContext(ctx context.Context) *DeleteBooksIsbnParams {
	return &DeleteBooksIsbnParams{
		Context: ctx,
	}
}

// NewDeleteBooksIsbnParamsWithHTTPClient creates a new DeleteBooksIsbnParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBooksIsbnParamsWithHTTPClient(client *http.Client) *DeleteBooksIsbnParams {
	return &DeleteBooksIsbnParams{
		HTTPClient: client,
	}
}

/*
DeleteBooksIsbnParams contains all the parameters to send to the API endpoint

	for the delete books isbn operation.

	Typically these are written to a http.Request.
*/
type DeleteBooksIsbnParams struct {

	/* Isbn.

	   isbn code
	*/
	Isbn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete books isbn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBooksIsbnParams) WithDefaults() *DeleteBooksIsbnParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete books isbn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBooksIsbnParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete books isbn params
func (o *DeleteBooksIsbnParams) WithTimeout(timeout time.Duration) *DeleteBooksIsbnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete books isbn params
func (o *DeleteBooksIsbnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete books isbn params
func (o *DeleteBooksIsbnParams) WithContext(ctx context.Context) *DeleteBooksIsbnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete books isbn params
func (o *DeleteBooksIsbnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete books isbn params
func (o *DeleteBooksIsbnParams) WithHTTPClient(client *http.Client) *DeleteBooksIsbnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete books isbn params
func (o *DeleteBooksIsbnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIsbn adds the isbn to the delete books isbn params
func (o *DeleteBooksIsbnParams) WithIsbn(isbn string) *DeleteBooksIsbnParams {
	o.SetIsbn(isbn)
	return o
}

// SetIsbn adds the isbn to the delete books isbn params
func (o *DeleteBooksIsbnParams) SetIsbn(isbn string) {
	o.Isbn = isbn
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBooksIsbnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param isbn
	if err := r.SetPathParam("isbn", o.Isbn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
