// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBooksIsbnParams creates a new GetBooksIsbnParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBooksIsbnParams() *GetBooksIsbnParams {
	return &GetBooksIsbnParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBooksIsbnParamsWithTimeout creates a new GetBooksIsbnParams object
// with the ability to set a timeout on a request.
func NewGetBooksIsbnParamsWithTimeout(timeout time.Duration) *GetBooksIsbnParams {
	return &GetBooksIsbnParams{
		timeout: timeout,
	}
}

// NewGetBooksIsbnParamsWithContext creates a new GetBooksIsbnParams object
// with the ability to set a context for a request.
func NewGetBooksIsbnParamsWithContext(ctx context.Context) *GetBooksIsbnParams {
	return &GetBooksIsbnParams{
		Context: ctx,
	}
}

// NewGetBooksIsbnParamsWithHTTPClient creates a new GetBooksIsbnParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBooksIsbnParamsWithHTTPClient(client *http.Client) *GetBooksIsbnParams {
	return &GetBooksIsbnParams{
		HTTPClient: client,
	}
}

/*
GetBooksIsbnParams contains all the parameters to send to the API endpoint

	for the get books isbn operation.

	Typically these are written to a http.Request.
*/
type GetBooksIsbnParams struct {

	/* Isbn.

	   isbn code
	*/
	Isbn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get books isbn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBooksIsbnParams) WithDefaults() *GetBooksIsbnParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get books isbn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBooksIsbnParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get books isbn params
func (o *GetBooksIsbnParams) WithTimeout(timeout time.Duration) *GetBooksIsbnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get books isbn params
func (o *GetBooksIsbnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get books isbn params
func (o *GetBooksIsbnParams) WithContext(ctx context.Context) *GetBooksIsbnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get books isbn params
func (o *GetBooksIsbnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get books isbn params
func (o *GetBooksIsbnParams) WithHTTPClient(client *http.Client) *GetBooksIsbnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get books isbn params
func (o *GetBooksIsbnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIsbn adds the isbn to the get books isbn params
func (o *GetBooksIsbnParams) WithIsbn(isbn string) *GetBooksIsbnParams {
	o.SetIsbn(isbn)
	return o
}

// SetIsbn adds the isbn to the get books isbn params
func (o *GetBooksIsbnParams) SetIsbn(isbn string) {
	o.Isbn = isbn
}

// WriteToRequest writes these params to a swagger request
func (o *GetBooksIsbnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param isbn
	if err := r.SetPathParam("isbn", o.Isbn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
