// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBooksParams creates a new GetBooksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBooksParams() *GetBooksParams {
	return &GetBooksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBooksParamsWithTimeout creates a new GetBooksParams object
// with the ability to set a timeout on a request.
func NewGetBooksParamsWithTimeout(timeout time.Duration) *GetBooksParams {
	return &GetBooksParams{
		timeout: timeout,
	}
}

// NewGetBooksParamsWithContext creates a new GetBooksParams object
// with the ability to set a context for a request.
func NewGetBooksParamsWithContext(ctx context.Context) *GetBooksParams {
	return &GetBooksParams{
		Context: ctx,
	}
}

// NewGetBooksParamsWithHTTPClient creates a new GetBooksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBooksParamsWithHTTPClient(client *http.Client) *GetBooksParams {
	return &GetBooksParams{
		HTTPClient: client,
	}
}

/*
GetBooksParams contains all the parameters to send to the API endpoint

	for the get books operation.

	Typically these are written to a http.Request.
*/
type GetBooksParams struct {

	// Filter.
	Filter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get books params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBooksParams) WithDefaults() *GetBooksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get books params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBooksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get books params
func (o *GetBooksParams) WithTimeout(timeout time.Duration) *GetBooksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get books params
func (o *GetBooksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get books params
func (o *GetBooksParams) WithContext(ctx context.Context) *GetBooksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get books params
func (o *GetBooksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get books params
func (o *GetBooksParams) WithHTTPClient(client *http.Client) *GetBooksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get books params
func (o *GetBooksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the get books params
func (o *GetBooksParams) WithFilter(filter *string) *GetBooksParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the get books params
func (o *GetBooksParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WriteToRequest writes these params to a swagger request
func (o *GetBooksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
