// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"librarian/models"
)

// GetBooksIsbnReader is a Reader for the GetBooksIsbn structure.
type GetBooksIsbnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBooksIsbnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBooksIsbnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetBooksIsbnNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetBooksIsbnDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBooksIsbnOK creates a GetBooksIsbnOK with default headers values
func NewGetBooksIsbnOK() *GetBooksIsbnOK {
	return &GetBooksIsbnOK{}
}

/*
GetBooksIsbnOK describes a response with status code 200, with default header values.

Book matching the requested isbn
*/
type GetBooksIsbnOK struct {
	Payload *models.Book
}

// IsSuccess returns true when this get books isbn o k response has a 2xx status code
func (o *GetBooksIsbnOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get books isbn o k response has a 3xx status code
func (o *GetBooksIsbnOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get books isbn o k response has a 4xx status code
func (o *GetBooksIsbnOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get books isbn o k response has a 5xx status code
func (o *GetBooksIsbnOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get books isbn o k response a status code equal to that given
func (o *GetBooksIsbnOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get books isbn o k response
func (o *GetBooksIsbnOK) Code() int {
	return 200
}

func (o *GetBooksIsbnOK) Error() string {
	return fmt.Sprintf("[GET /books/{isbn}][%d] getBooksIsbnOK  %+v", 200, o.Payload)
}

func (o *GetBooksIsbnOK) String() string {
	return fmt.Sprintf("[GET /books/{isbn}][%d] getBooksIsbnOK  %+v", 200, o.Payload)
}

func (o *GetBooksIsbnOK) GetPayload() *models.Book {
	return o.Payload
}

func (o *GetBooksIsbnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Book)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBooksIsbnNotFound creates a GetBooksIsbnNotFound with default headers values
func NewGetBooksIsbnNotFound() *GetBooksIsbnNotFound {
	return &GetBooksIsbnNotFound{}
}

/*
GetBooksIsbnNotFound describes a response with status code 404, with default header values.

Book not found.
*/
type GetBooksIsbnNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get books isbn not found response has a 2xx status code
func (o *GetBooksIsbnNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get books isbn not found response has a 3xx status code
func (o *GetBooksIsbnNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get books isbn not found response has a 4xx status code
func (o *GetBooksIsbnNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get books isbn not found response has a 5xx status code
func (o *GetBooksIsbnNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get books isbn not found response a status code equal to that given
func (o *GetBooksIsbnNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get books isbn not found response
func (o *GetBooksIsbnNotFound) Code() int {
	return 404
}

func (o *GetBooksIsbnNotFound) Error() string {
	return fmt.Sprintf("[GET /books/{isbn}][%d] getBooksIsbnNotFound  %+v", 404, o.Payload)
}

func (o *GetBooksIsbnNotFound) String() string {
	return fmt.Sprintf("[GET /books/{isbn}][%d] getBooksIsbnNotFound  %+v", 404, o.Payload)
}

func (o *GetBooksIsbnNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBooksIsbnNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBooksIsbnDefault creates a GetBooksIsbnDefault with default headers values
func NewGetBooksIsbnDefault(code int) *GetBooksIsbnDefault {
	return &GetBooksIsbnDefault{
		_statusCode: code,
	}
}

/*
GetBooksIsbnDefault describes a response with status code -1, with default header values.

bad input parametr/missing book
*/
type GetBooksIsbnDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get books isbn default response has a 2xx status code
func (o *GetBooksIsbnDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get books isbn default response has a 3xx status code
func (o *GetBooksIsbnDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get books isbn default response has a 4xx status code
func (o *GetBooksIsbnDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get books isbn default response has a 5xx status code
func (o *GetBooksIsbnDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get books isbn default response a status code equal to that given
func (o *GetBooksIsbnDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get books isbn default response
func (o *GetBooksIsbnDefault) Code() int {
	return o._statusCode
}

func (o *GetBooksIsbnDefault) Error() string {
	return fmt.Sprintf("[GET /books/{isbn}][%d] GetBooksIsbn default  %+v", o._statusCode, o.Payload)
}

func (o *GetBooksIsbnDefault) String() string {
	return fmt.Sprintf("[GET /books/{isbn}][%d] GetBooksIsbn default  %+v", o._statusCode, o.Payload)
}

func (o *GetBooksIsbnDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBooksIsbnDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
