// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"librarian/models"
)

// PutBooksIsbnReader is a Reader for the PutBooksIsbn structure.
type PutBooksIsbnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutBooksIsbnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutBooksIsbnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPutBooksIsbnDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutBooksIsbnOK creates a PutBooksIsbnOK with default headers values
func NewPutBooksIsbnOK() *PutBooksIsbnOK {
	return &PutBooksIsbnOK{}
}

/*
PutBooksIsbnOK describes a response with status code 200, with default header values.

Book matching the requested isbn
*/
type PutBooksIsbnOK struct {
	Payload *models.Book
}

// IsSuccess returns true when this put books isbn o k response has a 2xx status code
func (o *PutBooksIsbnOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put books isbn o k response has a 3xx status code
func (o *PutBooksIsbnOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put books isbn o k response has a 4xx status code
func (o *PutBooksIsbnOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put books isbn o k response has a 5xx status code
func (o *PutBooksIsbnOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put books isbn o k response a status code equal to that given
func (o *PutBooksIsbnOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put books isbn o k response
func (o *PutBooksIsbnOK) Code() int {
	return 200
}

func (o *PutBooksIsbnOK) Error() string {
	return fmt.Sprintf("[PUT /books/{isbn}][%d] putBooksIsbnOK  %+v", 200, o.Payload)
}

func (o *PutBooksIsbnOK) String() string {
	return fmt.Sprintf("[PUT /books/{isbn}][%d] putBooksIsbnOK  %+v", 200, o.Payload)
}

func (o *PutBooksIsbnOK) GetPayload() *models.Book {
	return o.Payload
}

func (o *PutBooksIsbnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Book)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutBooksIsbnDefault creates a PutBooksIsbnDefault with default headers values
func NewPutBooksIsbnDefault(code int) *PutBooksIsbnDefault {
	return &PutBooksIsbnDefault{
		_statusCode: code,
	}
}

/*
PutBooksIsbnDefault describes a response with status code -1, with default header values.

bad input parametr/missing book
*/
type PutBooksIsbnDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this put books isbn default response has a 2xx status code
func (o *PutBooksIsbnDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put books isbn default response has a 3xx status code
func (o *PutBooksIsbnDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put books isbn default response has a 4xx status code
func (o *PutBooksIsbnDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put books isbn default response has a 5xx status code
func (o *PutBooksIsbnDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put books isbn default response a status code equal to that given
func (o *PutBooksIsbnDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put books isbn default response
func (o *PutBooksIsbnDefault) Code() int {
	return o._statusCode
}

func (o *PutBooksIsbnDefault) Error() string {
	return fmt.Sprintf("[PUT /books/{isbn}][%d] PutBooksIsbn default  %+v", o._statusCode, o.Payload)
}

func (o *PutBooksIsbnDefault) String() string {
	return fmt.Sprintf("[PUT /books/{isbn}][%d] PutBooksIsbn default  %+v", o._statusCode, o.Payload)
}

func (o *PutBooksIsbnDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutBooksIsbnDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
