// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"librarian/models"
)

// NewPutBooksIsbnParams creates a new PutBooksIsbnParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutBooksIsbnParams() *PutBooksIsbnParams {
	return &PutBooksIsbnParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutBooksIsbnParamsWithTimeout creates a new PutBooksIsbnParams object
// with the ability to set a timeout on a request.
func NewPutBooksIsbnParamsWithTimeout(timeout time.Duration) *PutBooksIsbnParams {
	return &PutBooksIsbnParams{
		timeout: timeout,
	}
}

// NewPutBooksIsbnParamsWithContext creates a new PutBooksIsbnParams object
// with the ability to set a context for a request.
func NewPutBooksIsbnParamsWithContext(ctx context.Context) *PutBooksIsbnParams {
	return &PutBooksIsbnParams{
		Context: ctx,
	}
}

// NewPutBooksIsbnParamsWithHTTPClient creates a new PutBooksIsbnParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutBooksIsbnParamsWithHTTPClient(client *http.Client) *PutBooksIsbnParams {
	return &PutBooksIsbnParams{
		HTTPClient: client,
	}
}

/*
PutBooksIsbnParams contains all the parameters to send to the API endpoint

	for the put books isbn operation.

	Typically these are written to a http.Request.
*/
type PutBooksIsbnParams struct {

	// Body.
	Body *models.Book

	/* Isbn.

	   isbn code
	*/
	Isbn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put books isbn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBooksIsbnParams) WithDefaults() *PutBooksIsbnParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put books isbn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutBooksIsbnParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put books isbn params
func (o *PutBooksIsbnParams) WithTimeout(timeout time.Duration) *PutBooksIsbnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put books isbn params
func (o *PutBooksIsbnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put books isbn params
func (o *PutBooksIsbnParams) WithContext(ctx context.Context) *PutBooksIsbnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put books isbn params
func (o *PutBooksIsbnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put books isbn params
func (o *PutBooksIsbnParams) WithHTTPClient(client *http.Client) *PutBooksIsbnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put books isbn params
func (o *PutBooksIsbnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put books isbn params
func (o *PutBooksIsbnParams) WithBody(body *models.Book) *PutBooksIsbnParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put books isbn params
func (o *PutBooksIsbnParams) SetBody(body *models.Book) {
	o.Body = body
}

// WithIsbn adds the isbn to the put books isbn params
func (o *PutBooksIsbnParams) WithIsbn(isbn string) *PutBooksIsbnParams {
	o.SetIsbn(isbn)
	return o
}

// SetIsbn adds the isbn to the put books isbn params
func (o *PutBooksIsbnParams) SetIsbn(isbn string) {
	o.Isbn = isbn
}

// WriteToRequest writes these params to a swagger request
func (o *PutBooksIsbnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param isbn
	if err := r.SetPathParam("isbn", o.Isbn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
