// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCollectionsNameHandlerFunc turns a function with the right signature into a delete collections name handler
type DeleteCollectionsNameHandlerFunc func(DeleteCollectionsNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCollectionsNameHandlerFunc) Handle(params DeleteCollectionsNameParams) middleware.Responder {
	return fn(params)
}

// DeleteCollectionsNameHandler interface for that can handle valid delete collections name params
type DeleteCollectionsNameHandler interface {
	Handle(DeleteCollectionsNameParams) middleware.Responder
}

// NewDeleteCollectionsName creates a new http.Handler for the delete collections name operation
func NewDeleteCollectionsName(ctx *middleware.Context, handler DeleteCollectionsNameHandler) *DeleteCollectionsName {
	return &DeleteCollectionsName{Context: ctx, Handler: handler}
}

/*
	DeleteCollectionsName swagger:route DELETE /collections/{name} collections deleteCollectionsName

Delete collection by name
*/
type DeleteCollectionsName struct {
	Context *middleware.Context
	Handler DeleteCollectionsNameHandler
}

func (o *DeleteCollectionsName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCollectionsNameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
