// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"librarian/models"
)

// DeleteCollectionsNameNoContentCode is the HTTP code returned for type DeleteCollectionsNameNoContent
const DeleteCollectionsNameNoContentCode int = 204

/*
DeleteCollectionsNameNoContent No content on successful delete

swagger:response deleteCollectionsNameNoContent
*/
type DeleteCollectionsNameNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.Collection `json:"body,omitempty"`
}

// NewDeleteCollectionsNameNoContent creates DeleteCollectionsNameNoContent with default headers values
func NewDeleteCollectionsNameNoContent() *DeleteCollectionsNameNoContent {

	return &DeleteCollectionsNameNoContent{}
}

// WithPayload adds the payload to the delete collections name no content response
func (o *DeleteCollectionsNameNoContent) WithPayload(payload *models.Collection) *DeleteCollectionsNameNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete collections name no content response
func (o *DeleteCollectionsNameNoContent) SetPayload(payload *models.Collection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCollectionsNameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DeleteCollectionsNameDefault bad input parametr/missing collection

swagger:response deleteCollectionsNameDefault
*/
type DeleteCollectionsNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteCollectionsNameDefault creates DeleteCollectionsNameDefault with default headers values
func NewDeleteCollectionsNameDefault(code int) *DeleteCollectionsNameDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteCollectionsNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete collections name default response
func (o *DeleteCollectionsNameDefault) WithStatusCode(code int) *DeleteCollectionsNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete collections name default response
func (o *DeleteCollectionsNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete collections name default response
func (o *DeleteCollectionsNameDefault) WithPayload(payload *models.Error) *DeleteCollectionsNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete collections name default response
func (o *DeleteCollectionsNameDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCollectionsNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
