// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCollectionsNameHandlerFunc turns a function with the right signature into a get collections name handler
type GetCollectionsNameHandlerFunc func(GetCollectionsNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCollectionsNameHandlerFunc) Handle(params GetCollectionsNameParams) middleware.Responder {
	return fn(params)
}

// GetCollectionsNameHandler interface for that can handle valid get collections name params
type GetCollectionsNameHandler interface {
	Handle(GetCollectionsNameParams) middleware.Responder
}

// NewGetCollectionsName creates a new http.Handler for the get collections name operation
func NewGetCollectionsName(ctx *middleware.Context, handler GetCollectionsNameHandler) *GetCollectionsName {
	return &GetCollectionsName{Context: ctx, Handler: handler}
}

/*
	GetCollectionsName swagger:route GET /collections/{name} collections getCollectionsName

Find collection by name
*/
type GetCollectionsName struct {
	Context *middleware.Context
	Handler GetCollectionsNameHandler
}

func (o *GetCollectionsName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCollectionsNameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
