// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostCollectionsHandlerFunc turns a function with the right signature into a post collections handler
type PostCollectionsHandlerFunc func(PostCollectionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCollectionsHandlerFunc) Handle(params PostCollectionsParams) middleware.Responder {
	return fn(params)
}

// PostCollectionsHandler interface for that can handle valid post collections params
type PostCollectionsHandler interface {
	Handle(PostCollectionsParams) middleware.Responder
}

// NewPostCollections creates a new http.Handler for the post collections operation
func NewPostCollections(ctx *middleware.Context, handler PostCollectionsHandler) *PostCollections {
	return &PostCollections{Context: ctx, Handler: handler}
}

/*
	PostCollections swagger:route POST /collections collections postCollections

Create a collection
*/
type PostCollections struct {
	Context *middleware.Context
	Handler PostCollectionsHandler
}

func (o *PostCollections) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCollectionsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
