// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"librarian/models"
)

// PostCollectionsOKCode is the HTTP code returned for type PostCollectionsOK
const PostCollectionsOKCode int = 200

/*
PostCollectionsOK Created a collection

swagger:response postCollectionsOK
*/
type PostCollectionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Collection `json:"body,omitempty"`
}

// NewPostCollectionsOK creates PostCollectionsOK with default headers values
func NewPostCollectionsOK() *PostCollectionsOK {

	return &PostCollectionsOK{}
}

// WithPayload adds the payload to the post collections o k response
func (o *PostCollectionsOK) WithPayload(payload *models.Collection) *PostCollectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections o k response
func (o *PostCollectionsOK) SetPayload(payload *models.Collection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostCollectionsDefault bad input for collection

swagger:response postCollectionsDefault
*/
type PostCollectionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCollectionsDefault creates PostCollectionsDefault with default headers values
func NewPostCollectionsDefault(code int) *PostCollectionsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostCollectionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post collections default response
func (o *PostCollectionsDefault) WithStatusCode(code int) *PostCollectionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post collections default response
func (o *PostCollectionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post collections default response
func (o *PostCollectionsDefault) WithPayload(payload *models.Error) *PostCollectionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections default response
func (o *PostCollectionsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
