consumes:
    - application/json
info:
    description: Application to handle books and collection of books.
    title: A library handling application
    version: 0.1.0
produces:
    - application/json
schemes:
    - http
swagger: "2.0"

definitions:
  book:
    type: object
    required:
      - isbn
    properties:
      isbn:
        type: string
        example: '1593272200'
      title:
        type: string
        example: 'The Linux Programming Interface: A Linux and UNIX System Programming Handbook'
      author:
        type: string
        example: 'Michael Kerrisk'
      genre:
        type: string
        example: 'Programming manual'
      published:
        type: string
        format: date
        example: '2023-04-24'
  collection:
    type: object
    required:
      - name
      - isbn
    properties:
      name:
        type: string
        example: "19th century tech"
      isbn:
        type: string
        example: '1593272200'
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /books:
    get:
      tags:
        - books
      summary: Find book by isbn
      operationId: books_list
      responses:
        200:
          description: All books from the library.
          schema:
            type: array
            items:
              $ref: '#/definitions/book'
    post:
      tags:
        - books
      summary: Create a book
      operationId: create_book
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/book"
      responses:
        200:
          description: Created a book
          schema:
            $ref: '#/definitions/book'
        default:
          description: bad input for book
          schema:
            $ref: "#/definitions/error"

  /books/{isbn}:
    get:
      summary: Find book by isbn
      tags:
        - books
      parameters:
        - in: path
          name: isbn
          type: string
          required: true
          description: isbn code
      responses:
        200:
          description: Book matching the requested isbn
          schema:
            $ref: '#/definitions/book'
        default:
          description: bad input parametr/missing book
          schema:
            $ref: "#/definitions/error"
  /collections:
    get:
      summary: Find collection by its name
      responses:
        200:
          description: All collections from the library.
          schema:
            type: array
            items:
              $ref: '#/definitions/collection'
    post:
      tags:
        - collections
      summary: Create a collection
      operationId: create_collection
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/collection"
      responses:
        200:
          description: Created a collection
          schema:
            $ref: '#/definitions/collection'
        default:
          description: bad input for collection
          schema:
            $ref: "#/definitions/error"
