// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new collections API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for collections API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteCollections(params *DeleteCollectionsParams, opts ...ClientOption) (*DeleteCollectionsNoContent, error)

	GetCollections(params *GetCollectionsParams, opts ...ClientOption) (*GetCollectionsOK, error)

	PostCollections(params *PostCollectionsParams, opts ...ClientOption) (*PostCollectionsOK, error)

	PutCollections(params *PutCollectionsParams, opts ...ClientOption) (*PutCollectionsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteCollections deletes collection by name
*/
func (a *Client) DeleteCollections(params *DeleteCollectionsParams, opts ...ClientOption) (*DeleteCollectionsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteCollectionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteCollections",
		Method:             "DELETE",
		PathPattern:        "/collections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteCollectionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteCollectionsNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteCollectionsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
GetCollections gets one or all collections
*/
func (a *Client) GetCollections(params *GetCollectionsParams, opts ...ClientOption) (*GetCollectionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCollectionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetCollections",
		Method:             "GET",
		PathPattern:        "/collections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCollectionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCollectionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetCollectionsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostCollections creates a collection
*/
func (a *Client) PostCollections(params *PostCollectionsParams, opts ...ClientOption) (*PostCollectionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostCollectionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostCollections",
		Method:             "POST",
		PathPattern:        "/collections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostCollectionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostCollectionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostCollectionsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PutCollections updates collection
*/
func (a *Client) PutCollections(params *PutCollectionsParams, opts ...ClientOption) (*PutCollectionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutCollectionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutCollections",
		Method:             "PUT",
		PathPattern:        "/collections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutCollectionsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutCollectionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PutCollectionsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
