// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"librarian/models"
)

// DeleteCollectionsReader is a Reader for the DeleteCollections structure.
type DeleteCollectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCollectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteCollectionsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteCollectionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteCollectionsNoContent creates a DeleteCollectionsNoContent with default headers values
func NewDeleteCollectionsNoContent() *DeleteCollectionsNoContent {
	return &DeleteCollectionsNoContent{}
}

/*
DeleteCollectionsNoContent describes a response with status code 204, with default header values.

No content on successful delete
*/
type DeleteCollectionsNoContent struct {
	Payload *models.Collection
}

// IsSuccess returns true when this delete collections no content response has a 2xx status code
func (o *DeleteCollectionsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete collections no content response has a 3xx status code
func (o *DeleteCollectionsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete collections no content response has a 4xx status code
func (o *DeleteCollectionsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete collections no content response has a 5xx status code
func (o *DeleteCollectionsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete collections no content response a status code equal to that given
func (o *DeleteCollectionsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete collections no content response
func (o *DeleteCollectionsNoContent) Code() int {
	return 204
}

func (o *DeleteCollectionsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /collections][%d] deleteCollectionsNoContent  %+v", 204, o.Payload)
}

func (o *DeleteCollectionsNoContent) String() string {
	return fmt.Sprintf("[DELETE /collections][%d] deleteCollectionsNoContent  %+v", 204, o.Payload)
}

func (o *DeleteCollectionsNoContent) GetPayload() *models.Collection {
	return o.Payload
}

func (o *DeleteCollectionsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Collection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCollectionsDefault creates a DeleteCollectionsDefault with default headers values
func NewDeleteCollectionsDefault(code int) *DeleteCollectionsDefault {
	return &DeleteCollectionsDefault{
		_statusCode: code,
	}
}

/*
DeleteCollectionsDefault describes a response with status code -1, with default header values.

bad input parametr/missing collection
*/
type DeleteCollectionsDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this delete collections default response has a 2xx status code
func (o *DeleteCollectionsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete collections default response has a 3xx status code
func (o *DeleteCollectionsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete collections default response has a 4xx status code
func (o *DeleteCollectionsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete collections default response has a 5xx status code
func (o *DeleteCollectionsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete collections default response a status code equal to that given
func (o *DeleteCollectionsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete collections default response
func (o *DeleteCollectionsDefault) Code() int {
	return o._statusCode
}

func (o *DeleteCollectionsDefault) Error() string {
	return fmt.Sprintf("[DELETE /collections][%d] DeleteCollections default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteCollectionsDefault) String() string {
	return fmt.Sprintf("[DELETE /collections][%d] DeleteCollections default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteCollectionsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteCollectionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
