// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"librarian/models"
)

// NewPostCollectionsParams creates a new PostCollectionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCollectionsParams() *PostCollectionsParams {
	return &PostCollectionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCollectionsParamsWithTimeout creates a new PostCollectionsParams object
// with the ability to set a timeout on a request.
func NewPostCollectionsParamsWithTimeout(timeout time.Duration) *PostCollectionsParams {
	return &PostCollectionsParams{
		timeout: timeout,
	}
}

// NewPostCollectionsParamsWithContext creates a new PostCollectionsParams object
// with the ability to set a context for a request.
func NewPostCollectionsParamsWithContext(ctx context.Context) *PostCollectionsParams {
	return &PostCollectionsParams{
		Context: ctx,
	}
}

// NewPostCollectionsParamsWithHTTPClient creates a new PostCollectionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCollectionsParamsWithHTTPClient(client *http.Client) *PostCollectionsParams {
	return &PostCollectionsParams{
		HTTPClient: client,
	}
}

/*
PostCollectionsParams contains all the parameters to send to the API endpoint

	for the post collections operation.

	Typically these are written to a http.Request.
*/
type PostCollectionsParams struct {

	// Body.
	Body *models.Collection

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCollectionsParams) WithDefaults() *PostCollectionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCollectionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post collections params
func (o *PostCollectionsParams) WithTimeout(timeout time.Duration) *PostCollectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post collections params
func (o *PostCollectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post collections params
func (o *PostCollectionsParams) WithContext(ctx context.Context) *PostCollectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post collections params
func (o *PostCollectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post collections params
func (o *PostCollectionsParams) WithHTTPClient(client *http.Client) *PostCollectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post collections params
func (o *PostCollectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post collections params
func (o *PostCollectionsParams) WithBody(body *models.Collection) *PostCollectionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post collections params
func (o *PostCollectionsParams) SetBody(body *models.Collection) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostCollectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
