// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"librarian/models"
)

// PostCollectionsReader is a Reader for the PostCollections structure.
type PostCollectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCollectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostCollectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostCollectionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCollectionsOK creates a PostCollectionsOK with default headers values
func NewPostCollectionsOK() *PostCollectionsOK {
	return &PostCollectionsOK{}
}

/*
PostCollectionsOK describes a response with status code 200, with default header values.

Created a collection
*/
type PostCollectionsOK struct {
	Payload *models.Collection
}

// IsSuccess returns true when this post collections o k response has a 2xx status code
func (o *PostCollectionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post collections o k response has a 3xx status code
func (o *PostCollectionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post collections o k response has a 4xx status code
func (o *PostCollectionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post collections o k response has a 5xx status code
func (o *PostCollectionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post collections o k response a status code equal to that given
func (o *PostCollectionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post collections o k response
func (o *PostCollectionsOK) Code() int {
	return 200
}

func (o *PostCollectionsOK) Error() string {
	return fmt.Sprintf("[POST /collections][%d] postCollectionsOK  %+v", 200, o.Payload)
}

func (o *PostCollectionsOK) String() string {
	return fmt.Sprintf("[POST /collections][%d] postCollectionsOK  %+v", 200, o.Payload)
}

func (o *PostCollectionsOK) GetPayload() *models.Collection {
	return o.Payload
}

func (o *PostCollectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Collection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCollectionsDefault creates a PostCollectionsDefault with default headers values
func NewPostCollectionsDefault(code int) *PostCollectionsDefault {
	return &PostCollectionsDefault{
		_statusCode: code,
	}
}

/*
PostCollectionsDefault describes a response with status code -1, with default header values.

bad input for collection
*/
type PostCollectionsDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this post collections default response has a 2xx status code
func (o *PostCollectionsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post collections default response has a 3xx status code
func (o *PostCollectionsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post collections default response has a 4xx status code
func (o *PostCollectionsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post collections default response has a 5xx status code
func (o *PostCollectionsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post collections default response a status code equal to that given
func (o *PostCollectionsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post collections default response
func (o *PostCollectionsDefault) Code() int {
	return o._statusCode
}

func (o *PostCollectionsDefault) Error() string {
	return fmt.Sprintf("[POST /collections][%d] PostCollections default  %+v", o._statusCode, o.Payload)
}

func (o *PostCollectionsDefault) String() string {
	return fmt.Sprintf("[POST /collections][%d] PostCollections default  %+v", o._statusCode, o.Payload)
}

func (o *PostCollectionsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostCollectionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
