// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"librarian/client/books"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationBooksDeleteBooksIsbnCmd returns a cmd to handle operation deleteBooksIsbn
func makeOperationBooksDeleteBooksIsbnCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "DeleteBooksIsbn",
		Short: ``,
		RunE:  runOperationBooksDeleteBooksIsbn,
	}

	if err := registerOperationBooksDeleteBooksIsbnParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationBooksDeleteBooksIsbn uses cmd flags to call endpoint api
func runOperationBooksDeleteBooksIsbn(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := books.NewDeleteBooksIsbnParams()
	if err, _ := retrieveOperationBooksDeleteBooksIsbnIsbnFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationBooksDeleteBooksIsbnResult(appCli.Books.DeleteBooksIsbn(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationBooksDeleteBooksIsbnParamFlags registers all flags needed to fill params
func registerOperationBooksDeleteBooksIsbnParamFlags(cmd *cobra.Command) error {
	if err := registerOperationBooksDeleteBooksIsbnIsbnParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationBooksDeleteBooksIsbnIsbnParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	isbnDescription := `Required. isbn code`

	var isbnFlagName string
	if cmdPrefix == "" {
		isbnFlagName = "isbn"
	} else {
		isbnFlagName = fmt.Sprintf("%v.isbn", cmdPrefix)
	}

	var isbnFlagDefault string

	_ = cmd.PersistentFlags().String(isbnFlagName, isbnFlagDefault, isbnDescription)

	return nil
}

func retrieveOperationBooksDeleteBooksIsbnIsbnFlag(m *books.DeleteBooksIsbnParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("isbn") {

		var isbnFlagName string
		if cmdPrefix == "" {
			isbnFlagName = "isbn"
		} else {
			isbnFlagName = fmt.Sprintf("%v.isbn", cmdPrefix)
		}

		isbnFlagValue, err := cmd.Flags().GetString(isbnFlagName)
		if err != nil {
			return err, false
		}
		m.Isbn = isbnFlagValue

	}
	return nil, retAdded
}

// parseOperationBooksDeleteBooksIsbnResult parses request result and return the string content
func parseOperationBooksDeleteBooksIsbnResult(resp0 *books.DeleteBooksIsbnNoContent, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*books.DeleteBooksIsbnDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*books.DeleteBooksIsbnNoContent)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*books.DeleteBooksIsbnNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
