// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"librarian/client/collections"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationCollectionsGetCollectionsCmd returns a cmd to handle operation getCollections
func makeOperationCollectionsGetCollectionsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetCollections",
		Short: ``,
		RunE:  runOperationCollectionsGetCollections,
	}

	if err := registerOperationCollectionsGetCollectionsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationCollectionsGetCollections uses cmd flags to call endpoint api
func runOperationCollectionsGetCollections(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := collections.NewGetCollectionsParams()
	if err, _ := retrieveOperationCollectionsGetCollectionsNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationCollectionsGetCollectionsResult(appCli.Collections.GetCollections(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationCollectionsGetCollectionsParamFlags registers all flags needed to fill params
func registerOperationCollectionsGetCollectionsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationCollectionsGetCollectionsNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationCollectionsGetCollectionsNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `Name of collection`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}

func retrieveOperationCollectionsGetCollectionsNameFlag(m *collections.GetCollectionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = &nameFlagValue

	}
	return nil, retAdded
}

// parseOperationCollectionsGetCollectionsResult parses request result and return the string content
func parseOperationCollectionsGetCollectionsResult(resp0 *collections.GetCollectionsOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*collections.GetCollectionsDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*collections.GetCollectionsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*collections.GetCollectionsNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
