// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"librarian/client/collections"
	"librarian/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationCollectionsPostCollectionsCmd returns a cmd to handle operation postCollections
func makeOperationCollectionsPostCollectionsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostCollections",
		Short: ``,
		RunE:  runOperationCollectionsPostCollections,
	}

	if err := registerOperationCollectionsPostCollectionsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationCollectionsPostCollections uses cmd flags to call endpoint api
func runOperationCollectionsPostCollections(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := collections.NewPostCollectionsParams()
	if err, _ := retrieveOperationCollectionsPostCollectionsBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationCollectionsPostCollectionsResult(appCli.Collections.PostCollections(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationCollectionsPostCollectionsParamFlags registers all flags needed to fill params
func registerOperationCollectionsPostCollectionsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationCollectionsPostCollectionsBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationCollectionsPostCollectionsBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. ")

	// add flags for body
	if err := registerModelCollectionFlags(0, "collection", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationCollectionsPostCollectionsBodyFlag(m *collections.PostCollectionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.Collection{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.Collection: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.Collection{}
	}
	err, added := retrieveModelCollectionFlags(0, bodyValueModel, "collection", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationCollectionsPostCollectionsResult parses request result and return the string content
func parseOperationCollectionsPostCollectionsResult(resp0 *collections.PostCollectionsOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*collections.PostCollectionsDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*collections.PostCollectionsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
