// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"librarian/client/books"
	"librarian/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationBooksPostBooksCmd returns a cmd to handle operation postBooks
func makeOperationBooksPostBooksCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostBooks",
		Short: ``,
		RunE:  runOperationBooksPostBooks,
	}

	if err := registerOperationBooksPostBooksParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationBooksPostBooks uses cmd flags to call endpoint api
func runOperationBooksPostBooks(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := books.NewPostBooksParams()
	if err, _ := retrieveOperationBooksPostBooksBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationBooksPostBooksResult(appCli.Books.PostBooks(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationBooksPostBooksParamFlags registers all flags needed to fill params
func registerOperationBooksPostBooksParamFlags(cmd *cobra.Command) error {
	if err := registerOperationBooksPostBooksBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationBooksPostBooksBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. ")

	// add flags for body
	if err := registerModelBookFlags(0, "book", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationBooksPostBooksBodyFlag(m *books.PostBooksParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.Book{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.Book: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.Book{}
	}
	err, added := retrieveModelBookFlags(0, bodyValueModel, "book", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationBooksPostBooksResult parses request result and return the string content
func parseOperationBooksPostBooksResult(resp0 *books.PostBooksOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*books.PostBooksDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*books.PostBooksOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
