// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"librarian/client/collections"
	"librarian/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationCollectionsPutCollectionsCmd returns a cmd to handle operation putCollections
func makeOperationCollectionsPutCollectionsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PutCollections",
		Short: ``,
		RunE:  runOperationCollectionsPutCollections,
	}

	if err := registerOperationCollectionsPutCollectionsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationCollectionsPutCollections uses cmd flags to call endpoint api
func runOperationCollectionsPutCollections(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := collections.NewPutCollectionsParams()
	if err, _ := retrieveOperationCollectionsPutCollectionsBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationCollectionsPutCollectionsNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationCollectionsPutCollectionsResult(appCli.Collections.PutCollections(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationCollectionsPutCollectionsParamFlags registers all flags needed to fill params
func registerOperationCollectionsPutCollectionsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationCollectionsPutCollectionsBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationCollectionsPutCollectionsNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationCollectionsPutCollectionsBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. ")

	// add flags for body
	if err := registerModelCollectionFlags(0, "collection", cmd); err != nil {
		return err
	}

	return nil
}
func registerOperationCollectionsPutCollectionsNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `Required. Name of collection`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}

func retrieveOperationCollectionsPutCollectionsBodyFlag(m *collections.PutCollectionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.Collection{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.Collection: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.Collection{}
	}
	err, added := retrieveModelCollectionFlags(0, bodyValueModel, "collection", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}
func retrieveOperationCollectionsPutCollectionsNameFlag(m *collections.PutCollectionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = nameFlagValue

	}
	return nil, retAdded
}

// parseOperationCollectionsPutCollectionsResult parses request result and return the string content
func parseOperationCollectionsPutCollectionsResult(resp0 *collections.PutCollectionsOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*collections.PutCollectionsDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*collections.PutCollectionsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*collections.PutCollectionsNotFound)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
