// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"librarian/client/books"
	"librarian/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationBooksPutBooksIsbnCmd returns a cmd to handle operation putBooksIsbn
func makeOperationBooksPutBooksIsbnCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PutBooksIsbn",
		Short: ``,
		RunE:  runOperationBooksPutBooksIsbn,
	}

	if err := registerOperationBooksPutBooksIsbnParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationBooksPutBooksIsbn uses cmd flags to call endpoint api
func runOperationBooksPutBooksIsbn(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := books.NewPutBooksIsbnParams()
	if err, _ := retrieveOperationBooksPutBooksIsbnBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationBooksPutBooksIsbnIsbnFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationBooksPutBooksIsbnResult(appCli.Books.PutBooksIsbn(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationBooksPutBooksIsbnParamFlags registers all flags needed to fill params
func registerOperationBooksPutBooksIsbnParamFlags(cmd *cobra.Command) error {
	if err := registerOperationBooksPutBooksIsbnBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationBooksPutBooksIsbnIsbnParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationBooksPutBooksIsbnBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. ")

	// add flags for body
	if err := registerModelBookFlags(0, "book", cmd); err != nil {
		return err
	}

	return nil
}
func registerOperationBooksPutBooksIsbnIsbnParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	isbnDescription := `Required. isbn code`

	var isbnFlagName string
	if cmdPrefix == "" {
		isbnFlagName = "isbn"
	} else {
		isbnFlagName = fmt.Sprintf("%v.isbn", cmdPrefix)
	}

	var isbnFlagDefault string

	_ = cmd.PersistentFlags().String(isbnFlagName, isbnFlagDefault, isbnDescription)

	return nil
}

func retrieveOperationBooksPutBooksIsbnBodyFlag(m *books.PutBooksIsbnParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.Book{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.Book: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.Book{}
	}
	err, added := retrieveModelBookFlags(0, bodyValueModel, "book", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}
func retrieveOperationBooksPutBooksIsbnIsbnFlag(m *books.PutBooksIsbnParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("isbn") {

		var isbnFlagName string
		if cmdPrefix == "" {
			isbnFlagName = "isbn"
		} else {
			isbnFlagName = fmt.Sprintf("%v.isbn", cmdPrefix)
		}

		isbnFlagValue, err := cmd.Flags().GetString(isbnFlagName)
		if err != nil {
			return err, false
		}
		m.Isbn = isbnFlagValue

	}
	return nil, retAdded
}

// parseOperationBooksPutBooksIsbnResult parses request result and return the string content
func parseOperationBooksPutBooksIsbnResult(resp0 *books.PutBooksIsbnOK, respErr error) (string, error) {
	if respErr != nil {

		var iRespD interface{} = respErr
		respD, ok := iRespD.(*books.PutBooksIsbnDefault)
		if ok {
			if !swag.IsZero(respD) && !swag.IsZero(respD.Payload) {
				msgStr, err := json.Marshal(respD.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*books.PutBooksIsbnOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
