// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"librarian/models"
)

// GetCollectionsOKCode is the HTTP code returned for type GetCollectionsOK
const GetCollectionsOKCode int = 200

/*
GetCollectionsOK All collections from the library.

swagger:response getCollectionsOK
*/
type GetCollectionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Collection `json:"body,omitempty"`
}

// NewGetCollectionsOK creates GetCollectionsOK with default headers values
func NewGetCollectionsOK() *GetCollectionsOK {

	return &GetCollectionsOK{}
}

// WithPayload adds the payload to the get collections o k response
func (o *GetCollectionsOK) WithPayload(payload []*models.Collection) *GetCollectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collections o k response
func (o *GetCollectionsOK) SetPayload(payload []*models.Collection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Collection, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetCollectionsDefault bad input parametr/missing collection

swagger:response getCollectionsDefault
*/
type GetCollectionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCollectionsDefault creates GetCollectionsDefault with default headers values
func NewGetCollectionsDefault(code int) *GetCollectionsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCollectionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get collections default response
func (o *GetCollectionsDefault) WithStatusCode(code int) *GetCollectionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get collections default response
func (o *GetCollectionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get collections default response
func (o *GetCollectionsDefault) WithPayload(payload *models.Error) *GetCollectionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collections default response
func (o *GetCollectionsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
