// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"librarian/restapi/operations/books"
	"librarian/restapi/operations/collections"
)

// NewLibrarianAPI creates a new Librarian instance
func NewLibrarianAPI(spec *loads.Document) *LibrarianAPI {
	return &LibrarianAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		BooksDeleteBooksIsbnHandler: books.DeleteBooksIsbnHandlerFunc(func(params books.DeleteBooksIsbnParams) middleware.Responder {
			return middleware.NotImplemented("operation books.DeleteBooksIsbn has not yet been implemented")
		}),
		CollectionsDeleteCollectionsHandler: collections.DeleteCollectionsHandlerFunc(func(params collections.DeleteCollectionsParams) middleware.Responder {
			return middleware.NotImplemented("operation collections.DeleteCollections has not yet been implemented")
		}),
		BooksGetBooksHandler: books.GetBooksHandlerFunc(func(params books.GetBooksParams) middleware.Responder {
			return middleware.NotImplemented("operation books.GetBooks has not yet been implemented")
		}),
		BooksGetBooksIsbnHandler: books.GetBooksIsbnHandlerFunc(func(params books.GetBooksIsbnParams) middleware.Responder {
			return middleware.NotImplemented("operation books.GetBooksIsbn has not yet been implemented")
		}),
		CollectionsGetCollectionsHandler: collections.GetCollectionsHandlerFunc(func(params collections.GetCollectionsParams) middleware.Responder {
			return middleware.NotImplemented("operation collections.GetCollections has not yet been implemented")
		}),
		BooksPostBooksHandler: books.PostBooksHandlerFunc(func(params books.PostBooksParams) middleware.Responder {
			return middleware.NotImplemented("operation books.PostBooks has not yet been implemented")
		}),
		CollectionsPostCollectionsHandler: collections.PostCollectionsHandlerFunc(func(params collections.PostCollectionsParams) middleware.Responder {
			return middleware.NotImplemented("operation collections.PostCollections has not yet been implemented")
		}),
		BooksPutBooksIsbnHandler: books.PutBooksIsbnHandlerFunc(func(params books.PutBooksIsbnParams) middleware.Responder {
			return middleware.NotImplemented("operation books.PutBooksIsbn has not yet been implemented")
		}),
		CollectionsPutCollectionsHandler: collections.PutCollectionsHandlerFunc(func(params collections.PutCollectionsParams) middleware.Responder {
			return middleware.NotImplemented("operation collections.PutCollections has not yet been implemented")
		}),
	}
}

/*LibrarianAPI Application to handle books and collection of books. */
type LibrarianAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BooksDeleteBooksIsbnHandler sets the operation handler for the delete books isbn operation
	BooksDeleteBooksIsbnHandler books.DeleteBooksIsbnHandler
	// CollectionsDeleteCollectionsHandler sets the operation handler for the delete collections operation
	CollectionsDeleteCollectionsHandler collections.DeleteCollectionsHandler
	// BooksGetBooksHandler sets the operation handler for the get books operation
	BooksGetBooksHandler books.GetBooksHandler
	// BooksGetBooksIsbnHandler sets the operation handler for the get books isbn operation
	BooksGetBooksIsbnHandler books.GetBooksIsbnHandler
	// CollectionsGetCollectionsHandler sets the operation handler for the get collections operation
	CollectionsGetCollectionsHandler collections.GetCollectionsHandler
	// BooksPostBooksHandler sets the operation handler for the post books operation
	BooksPostBooksHandler books.PostBooksHandler
	// CollectionsPostCollectionsHandler sets the operation handler for the post collections operation
	CollectionsPostCollectionsHandler collections.PostCollectionsHandler
	// BooksPutBooksIsbnHandler sets the operation handler for the put books isbn operation
	BooksPutBooksIsbnHandler books.PutBooksIsbnHandler
	// CollectionsPutCollectionsHandler sets the operation handler for the put collections operation
	CollectionsPutCollectionsHandler collections.PutCollectionsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *LibrarianAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *LibrarianAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *LibrarianAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *LibrarianAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *LibrarianAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *LibrarianAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *LibrarianAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *LibrarianAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *LibrarianAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the LibrarianAPI
func (o *LibrarianAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BooksDeleteBooksIsbnHandler == nil {
		unregistered = append(unregistered, "books.DeleteBooksIsbnHandler")
	}
	if o.CollectionsDeleteCollectionsHandler == nil {
		unregistered = append(unregistered, "collections.DeleteCollectionsHandler")
	}
	if o.BooksGetBooksHandler == nil {
		unregistered = append(unregistered, "books.GetBooksHandler")
	}
	if o.BooksGetBooksIsbnHandler == nil {
		unregistered = append(unregistered, "books.GetBooksIsbnHandler")
	}
	if o.CollectionsGetCollectionsHandler == nil {
		unregistered = append(unregistered, "collections.GetCollectionsHandler")
	}
	if o.BooksPostBooksHandler == nil {
		unregistered = append(unregistered, "books.PostBooksHandler")
	}
	if o.CollectionsPostCollectionsHandler == nil {
		unregistered = append(unregistered, "collections.PostCollectionsHandler")
	}
	if o.BooksPutBooksIsbnHandler == nil {
		unregistered = append(unregistered, "books.PutBooksIsbnHandler")
	}
	if o.CollectionsPutCollectionsHandler == nil {
		unregistered = append(unregistered, "collections.PutCollectionsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *LibrarianAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *LibrarianAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *LibrarianAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *LibrarianAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *LibrarianAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *LibrarianAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the librarian API
func (o *LibrarianAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *LibrarianAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/books/{isbn}"] = books.NewDeleteBooksIsbn(o.context, o.BooksDeleteBooksIsbnHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/collections"] = collections.NewDeleteCollections(o.context, o.CollectionsDeleteCollectionsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/books"] = books.NewGetBooks(o.context, o.BooksGetBooksHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/books/{isbn}"] = books.NewGetBooksIsbn(o.context, o.BooksGetBooksIsbnHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/collections"] = collections.NewGetCollections(o.context, o.CollectionsGetCollectionsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/books"] = books.NewPostBooks(o.context, o.BooksPostBooksHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/collections"] = collections.NewPostCollections(o.context, o.CollectionsPostCollectionsHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/books/{isbn}"] = books.NewPutBooksIsbn(o.context, o.BooksPutBooksIsbnHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/collections"] = collections.NewPutCollections(o.context, o.CollectionsPutCollectionsHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *LibrarianAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *LibrarianAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *LibrarianAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *LibrarianAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *LibrarianAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
