// Code generated by go-swagger; DO NOT EDIT.

// Package restapi A library handling application
//
//	Application to handle books and collection of books.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
