// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteBooksIsbnParams creates a new DeleteBooksIsbnParams object
//
// There are no default values defined in the spec.
func NewDeleteBooksIsbnParams() DeleteBooksIsbnParams {

	return DeleteBooksIsbnParams{}
}

// DeleteBooksIsbnParams contains all the bound params for the delete books isbn operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteBooksIsbn
type DeleteBooksIsbnParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*isbn code
	  Required: true
	  In: path
	*/
	Isbn string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteBooksIsbnParams() beforehand.
func (o *DeleteBooksIsbnParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rIsbn, rhkIsbn, _ := route.Params.GetOK("isbn")
	if err := o.bindIsbn(rIsbn, rhkIsbn, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIsbn binds and validates parameter Isbn from path.
func (o *DeleteBooksIsbnParams) bindIsbn(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Isbn = raw

	return nil
}
