// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"librarian/models"
)

// GetBooksIsbnOKCode is the HTTP code returned for type GetBooksIsbnOK
const GetBooksIsbnOKCode int = 200

/*
GetBooksIsbnOK Book matching the requested isbn

swagger:response getBooksIsbnOK
*/
type GetBooksIsbnOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewGetBooksIsbnOK creates GetBooksIsbnOK with default headers values
func NewGetBooksIsbnOK() *GetBooksIsbnOK {

	return &GetBooksIsbnOK{}
}

// WithPayload adds the payload to the get books isbn o k response
func (o *GetBooksIsbnOK) WithPayload(payload *models.Book) *GetBooksIsbnOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books isbn o k response
func (o *GetBooksIsbnOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIsbnOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBooksIsbnNotFoundCode is the HTTP code returned for type GetBooksIsbnNotFound
const GetBooksIsbnNotFoundCode int = 404

/*
GetBooksIsbnNotFound Book not found.

swagger:response getBooksIsbnNotFound
*/
type GetBooksIsbnNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBooksIsbnNotFound creates GetBooksIsbnNotFound with default headers values
func NewGetBooksIsbnNotFound() *GetBooksIsbnNotFound {

	return &GetBooksIsbnNotFound{}
}

// WithPayload adds the payload to the get books isbn not found response
func (o *GetBooksIsbnNotFound) WithPayload(payload *models.Error) *GetBooksIsbnNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books isbn not found response
func (o *GetBooksIsbnNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIsbnNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetBooksIsbnDefault bad input parametr/missing book

swagger:response getBooksIsbnDefault
*/
type GetBooksIsbnDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBooksIsbnDefault creates GetBooksIsbnDefault with default headers values
func NewGetBooksIsbnDefault(code int) *GetBooksIsbnDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBooksIsbnDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get books isbn default response
func (o *GetBooksIsbnDefault) WithStatusCode(code int) *GetBooksIsbnDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get books isbn default response
func (o *GetBooksIsbnDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get books isbn default response
func (o *GetBooksIsbnDefault) WithPayload(payload *models.Error) *GetBooksIsbnDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books isbn default response
func (o *GetBooksIsbnDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIsbnDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
