// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBooksIsbnHandlerFunc turns a function with the right signature into a get books isbn handler
type GetBooksIsbnHandlerFunc func(GetBooksIsbnParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBooksIsbnHandlerFunc) Handle(params GetBooksIsbnParams) middleware.Responder {
	return fn(params)
}

// GetBooksIsbnHandler interface for that can handle valid get books isbn params
type GetBooksIsbnHandler interface {
	Handle(GetBooksIsbnParams) middleware.Responder
}

// NewGetBooksIsbn creates a new http.Handler for the get books isbn operation
func NewGetBooksIsbn(ctx *middleware.Context, handler GetBooksIsbnHandler) *GetBooksIsbn {
	return &GetBooksIsbn{Context: ctx, Handler: handler}
}

/*
	GetBooksIsbn swagger:route GET /books/{isbn} books getBooksIsbn

Find book by isbn
*/
type GetBooksIsbn struct {
	Context *middleware.Context
	Handler GetBooksIsbnHandler
}

func (o *GetBooksIsbn) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBooksIsbnParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
