// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutBooksIsbnHandlerFunc turns a function with the right signature into a put books isbn handler
type PutBooksIsbnHandlerFunc func(PutBooksIsbnParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutBooksIsbnHandlerFunc) Handle(params PutBooksIsbnParams) middleware.Responder {
	return fn(params)
}

// PutBooksIsbnHandler interface for that can handle valid put books isbn params
type PutBooksIsbnHandler interface {
	Handle(PutBooksIsbnParams) middleware.Responder
}

// NewPutBooksIsbn creates a new http.Handler for the put books isbn operation
func NewPutBooksIsbn(ctx *middleware.Context, handler PutBooksIsbnHandler) *PutBooksIsbn {
	return &PutBooksIsbn{Context: ctx, Handler: handler}
}

/*
	PutBooksIsbn swagger:route PUT /books/{isbn} books putBooksIsbn

Update book by isbn
*/
type PutBooksIsbn struct {
	Context *middleware.Context
	Handler PutBooksIsbnHandler
}

func (o *PutBooksIsbn) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutBooksIsbnParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
