// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"librarian/models"
)

// NewPutBooksIsbnParams creates a new PutBooksIsbnParams object
//
// There are no default values defined in the spec.
func NewPutBooksIsbnParams() PutBooksIsbnParams {

	return PutBooksIsbnParams{}
}

// PutBooksIsbnParams contains all the bound params for the put books isbn operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutBooksIsbn
type PutBooksIsbnParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Body *models.Book
	/*isbn code
	  Required: true
	  In: path
	*/
	Isbn string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutBooksIsbnParams() beforehand.
func (o *PutBooksIsbnParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Book
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	}

	rIsbn, rhkIsbn, _ := route.Params.GetOK("isbn")
	if err := o.bindIsbn(rIsbn, rhkIsbn, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIsbn binds and validates parameter Isbn from path.
func (o *PutBooksIsbnParams) bindIsbn(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Isbn = raw

	return nil
}
