// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"librarian/models"
)

// PutBooksIsbnOKCode is the HTTP code returned for type PutBooksIsbnOK
const PutBooksIsbnOKCode int = 200

/*
PutBooksIsbnOK Book matching the requested isbn

swagger:response putBooksIsbnOK
*/
type PutBooksIsbnOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewPutBooksIsbnOK creates PutBooksIsbnOK with default headers values
func NewPutBooksIsbnOK() *PutBooksIsbnOK {

	return &PutBooksIsbnOK{}
}

// WithPayload adds the payload to the put books isbn o k response
func (o *PutBooksIsbnOK) WithPayload(payload *models.Book) *PutBooksIsbnOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put books isbn o k response
func (o *PutBooksIsbnOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBooksIsbnOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PutBooksIsbnDefault bad input parametr/missing book

swagger:response putBooksIsbnDefault
*/
type PutBooksIsbnDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutBooksIsbnDefault creates PutBooksIsbnDefault with default headers values
func NewPutBooksIsbnDefault(code int) *PutBooksIsbnDefault {
	if code <= 0 {
		code = 500
	}

	return &PutBooksIsbnDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put books isbn default response
func (o *PutBooksIsbnDefault) WithStatusCode(code int) *PutBooksIsbnDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put books isbn default response
func (o *PutBooksIsbnDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put books isbn default response
func (o *PutBooksIsbnDefault) WithPayload(payload *models.Error) *PutBooksIsbnDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put books isbn default response
func (o *PutBooksIsbnDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBooksIsbnDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
